# Generated by Django 5.2.6 on 2025-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_name_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_nonce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
