# Generated by Django 5.2.6 on 2025-09-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_login_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
