# Generated by Django 5.2.6 on 2025-09-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_nonce_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_r2_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_r2_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
