# Generated by Django 5.2.6 on 2025-09-28 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_image_r2_key_product_image_r2_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mint',
            field=models.CharField(default='4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU', max_length=44),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='CZmkNn3pixHtcWF5dRPY87Pd2uyJWrvgtN8rmbiQGGkZ', max_length=44),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.product'),
        ),
    ]
