# Generated by Django 5.2.6 on 2025-09-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_orderitem_product'),
        ('core', '0007_product_mint_product_vendor_alter_orderitem_product'),
    ]

    operations = [
    ]
