# Generated by Django 5.2.6 on 2025-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20250928_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_r2_key',
            field=models.CharField(blank=True, default='a5d999d91a53c8f2f26db7ace5d3d49054e5bc8c8473cb9cdf6f2d7e6fcca8ca', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_r2_url',
            field=models.URLField(blank=True, default='https://e4983a6e7e4fe73a7f9f50e24e562975.r2.cloudflarestorage.com', null=True),
        ),
    ]
